name: Node.js Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: ['main']

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: evolianka/workflows/.github/workflows/publish-package.yml@main
